# Generated by Django 3.2.23 on 2023-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_movie_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=100)),
            ],
        ),
    ]
